run:
  deadline: 30s 

linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - gocognit
    - nilnil
    - paralleltest

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/macabu/inamedparam)
    section-separators:
      - newLine
